describe("Teste: gerir materiais.", () => {

    it('Efetuar login.', () => {
        cy.visit('/')
        cy.wait(3000)
        cy.get('[data-cy=menu]').click()
        cy.wait(1000)
        cy.get('[data-cy=entrar]').click()
        cy.get('[data-cy=email]').type('admin@email.com')
        cy.get('[data-cy=senha]').type('Admin123;')
        cy.wait(1000)
        cy.get('[data-cy=confirmar]').click()
    });

    it('Cadastrar fornecedor.', () => {
        cy.wait(3000)
        cy.contains('div', 'Fornecedores').parent('div').click()
        cy.wait(3000)
        cy.get('[data-cy=adicionar]').click()
        cy.get('[data-cy=nome]').type('Fornecedor 01')
        cy.get('[data-cy=cnpj]').type('71.831.789/0001-70')
        cy.get('[data-cy=categoria]').click()
        cy.wait(1000)
        cy.contains('div', 'Acabamento').parent('div').click()
        cy.get('[data-cy=confirmar]').click()
        cy.wait(3000)
        cy.get('[data-cy=adicionar]').click()
        cy.get('[data-cy=nome]').type('Fornecedor 02')
        cy.get('[data-cy=cnpj]').type('57.168.450/0001-05')
        cy.get('[data-cy=categoria]').click()
        cy.wait(1000)
        cy.contains('div', 'Alvenaria').parent('div').click()
        cy.get('[data-cy=confirmar]').click()


    });

    it('Cadastrar precificação.', () => {
        cy.wait(3000)
        cy.contains('div', 'Precificações').parent('div').click()
        cy.wait(3000)
        cy.get('[data-cy=adicionar]').click()
        cy.get('[data-cy=precificacao]').type('Precificação 01')
        cy.get('[data-cy=porcentagem]').type('25')
        cy.get('[data-cy=confirmar]').click()
        cy.wait(3000)
        cy.get('[data-cy=adicionar]').click()
        cy.get('[data-cy=precificacao]').type('Precificação 02')
        cy.get('[data-cy=porcentagem]').type('50')
        cy.get('[data-cy=confirmar]').click()
    });

    it('Cadastrar material.', () => {
        cy.wait(3000)
        cy.get('[href="/DashboardAdminMaterial"]').click()
        cy.wait(3000)
        cy.get('[data-cy=adicionar]').click()
        cy.get('[data-cy=descricao]').type('Material 01')
        cy.get('[data-cy=categoria]').click()
        cy.wait(1000)
        cy.contains('div', 'Acabamento').parent('div').click()
        cy.get('[data-cy=custo]').type('10')
        cy.get('[data-cy=precificacao]').click()
        cy.wait(1000)
        cy.contains('div', 'Precificação 01').parent('div').click()
        cy.get('[data-cy=fornecedor]').click()
        cy.wait(1000)
        cy.contains('div', 'Fornecedor 01').parent('div').click()
        cy.get('[data-cy=quantidade]').type('10000')
        cy.get('[data-cy=confirmar]').click()
        cy.wait(3000)
        cy.get('[data-cy=adicionar]').click()
        cy.get('[data-cy=descricao]').type('Material 02')
        cy.get('[data-cy=categoria]').click()
        cy.wait(1000)
        cy.contains('div', 'Alvenaria').parent('div').click()
        cy.get('[data-cy=custo]').type('15')
        cy.get('[data-cy=precificacao]').click()
        cy.wait(1000)
        cy.contains('div', 'Precificação 02').parent('div').click()
        cy.get('[data-cy=fornecedor]').click()
        cy.wait(1000)
        cy.contains('div', 'Fornecedor 02').parent('div').click()
        cy.get('[data-cy=quantidade]').type('15000')
        cy.get('[data-cy=confirmar]').click()
    });
})